vscode:
  extensions:
    - astro-build.astro-vscode
    - sourcegraph.cody-ai
    - bradlc.vscode-tailwindcss
    - mhutchie.git-graph
    - github.vscode-github-actions

tasks:
  - init: |
      echo 'KEYSTATIC=true' > .env
