image: gitpod/workspace-bun

tasks:
  - name: Prepare & Start Dev Server
    env:
      KEYSTATIC: true
    init: bun install --frozen-lockfile # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: bun run dev

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Development Server
    description: Astro's Dev Server at port 4321
    port: 4321
    onOpen: notify
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
vscode:
  extensions:
    - astro-build.astro-vscode
    - bradlc.vscode-tailwindcss
    - github.vscode-github-actions
    - astro-build.houston
    - vscode-icons-team.vscode-icons
