# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Prepare & Start Dev Server
    env:
      KEYSTATIC: true
    init: npm install # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: npm run dev

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Development Server
    description: Astro's Dev Server at port 4321
    port: 4321
    onOpen: notify
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
